# Generated by Django 4.0.1 on 2022-01-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_alter_user_user_type_user_user_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
