# Generated by Django 4.0.1 on 2022-01-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='impresstion_on_picture',
            new_name='impression_on_picture',
        ),
    ]
