# Generated by Django 4.0.1 on 2022-01-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_rename_impresstion_on_picture_vote_impression_on_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='impression_on_picture',
            new_name='impresstion_on_picture',
        ),
    ]
